# Generated by Django 5.1.7 on 2026-03-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='middle_name',
            new_name='patronymic',
        ),
        migrations.RenameField(
            model_name='historicalcustomuser',
            old_name='middle_name',
            new_name='patronymic',
        ),
    ]
