# Generated by Django 6.0.4 on 2026-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('deleted', 'Удален')], default='active', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('deleted', 'Удален')], default='active', max_length=24, verbose_name='Статус'),
        ),
    ]
