# Generated by Django 5.1.7 on 2026-03-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_org_customuser_org_historicalcustomuser_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='full_title',
            field=models.TextField(blank=True, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='org',
            name='title',
            field=models.CharField(help_text='20 симв.', max_length=20, verbose_name='Короткое название'),
        ),
    ]
