# Generated by Django 6.0.4 on 2026-05-04 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
    ]
