# Generated by Django 5.1.7 on 2026-04-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_org_full_title_alter_org_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='org',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='org',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.role', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.role', verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='Org',
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
