# Generated by Django 5.1.7 on 2026-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_role_remove_customuser_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=123, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='phone',
            field=models.CharField(default=123, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
