# Generated by Django 5.1.7 on 2026-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=123421, max_length=50, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='phone',
            field=models.CharField(db_index=True, default=12412, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
