# Generated by Django 5.1.7 on 2026-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
