# Generated by Django 6.0.4 on 2026-05-04 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('profile', '0002_alter_auditlog_action_alter_auditlog_actor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=24, null=True)),
                ('seller_type', models.CharField(choices=[('private', 'Частное лицо'), ('business', 'Бизнес')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На модерации'), ('active', 'Активно'), ('paused', 'На паузе'), ('sold', 'Продано'), ('rejected', 'Отклонено'), ('deleted', 'Удалено')], default='draft', max_length=24)),
                ('negotiable', models.BooleanField(default=False)),
                ('district', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('contacts_count', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('boosted_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_category_listings', to='admin_panel.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_listings', to='profile.city')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_listings', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_subcategory_listings', to='admin_panel.category')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='BoardFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='board.boardlisting')),
            ],
        ),
        migrations.CreateModel(
            name='BoardListingAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_num', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='board.boardlisting')),
            ],
        ),
        migrations.CreateModel(
            name='BoardListingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='board.boardlisting')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.mediafile')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BoardListingStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('contacts', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_daily', to='board.boardlisting')),
            ],
        ),
        migrations.CreateModel(
            name='BoardReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=80)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Новая'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.boardlisting')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=models.Index(fields=['city', 'status', 'created_at'], name='board_board_city_id_85c373_idx'),
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=models.Index(fields=['category', 'status'], name='board_board_categor_12d7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=models.Index(fields=['subcategory'], name='board_board_subcate_46e53f_idx'),
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=models.Index(fields=['price'], name='board_board_price_4462db_idx'),
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=models.Index(fields=['seller', 'status'], name='board_board_seller__043973_idx'),
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=models.Index(fields=['boosted_until'], name='board_board_boosted_d6e534_idx'),
        ),
        migrations.AddIndex(
            model_name='boardfavorite',
            index=models.Index(fields=['user', 'created_at'], name='board_board_user_id_a015e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_board_favorite'),
        ),
        migrations.AddIndex(
            model_name='boardlistingattribute',
            index=models.Index(fields=['listing', 'key'], name='board_board_listing_c0e432_idx'),
        ),
        migrations.AddIndex(
            model_name='boardlistingstatsdaily',
            index=models.Index(fields=['listing', 'day'], name='board_board_listing_bb526b_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardlistingstatsdaily',
            constraint=models.UniqueConstraint(fields=('listing', 'day'), name='unique_board_listing_stats_day'),
        ),
        migrations.AddIndex(
            model_name='boardreport',
            index=models.Index(fields=['listing'], name='board_board_listing_7bbafe_idx'),
        ),
        migrations.AddIndex(
            model_name='boardreport',
            index=models.Index(fields=['status', 'created_at'], name='board_board_status_995a6b_idx'),
        ),
    ]
