# Generated by Django 6.0.4 on 2026-05-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardfavorite',
            options={'verbose_name': 'Избранное объявление', 'verbose_name_plural': 'Избранные объявления'},
        ),
        migrations.AlterModelOptions(
            name='boardlistingattribute',
            options={'verbose_name': 'Характеристика объявления', 'verbose_name_plural': 'Характеристики объявлений'},
        ),
        migrations.AlterModelOptions(
            name='boardlistingmedia',
            options={'ordering': ['sort_order'], 'verbose_name': 'Медиа объявления', 'verbose_name_plural': 'Медиа объявлений'},
        ),
        migrations.AlterModelOptions(
            name='boardlistingstatsdaily',
            options={'verbose_name': 'Статистика объявления за день', 'verbose_name_plural': 'Статистика объявлений за дни'},
        ),
        migrations.AlterModelOptions(
            name='boardreport',
            options={'verbose_name': 'Жалоба на объявление', 'verbose_name_plural': 'Жалобы на объявления'},
        ),
    ]
