# Generated by Django 6.0.4 on 2026-05-04 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_adcampaign_budget_spent_and_more'),
        ('board', '0002_alter_boardfavorite_options_and_more'),
        ('profile', '0003_alter_auditlog_id_alter_mediafile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='boardfavorite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID избранного'),
        ),
        migrations.AlterField(
            model_name='boardfavorite',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='board.boardlisting', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='boardfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='boosted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Поднято до'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_category_listings', to='admin_panel.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_listings', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=24, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='contacts_count',
            field=models.IntegerField(default=0, verbose_name='Количество обращений'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='favorites_count',
            field=models.IntegerField(default=0, verbose_name='Количество добавлений в избранное'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объявления'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='Возможен торг'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_listings', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='seller_type',
            field=models.CharField(choices=[('private', 'Частное лицо'), ('business', 'Бизнес')], max_length=24, verbose_name='Тип продавца'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На модерации'), ('active', 'Активно'), ('paused', 'На паузе'), ('sold', 'Продано'), ('rejected', 'Отклонено'), ('deleted', 'Удалено')], default='draft', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_subcategory_listings', to='admin_panel.category', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='title',
            field=models.CharField(max_length=240, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='boardlisting',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='boardlistingattribute',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID характеристики'),
        ),
        migrations.AlterField(
            model_name='boardlistingattribute',
            name='key',
            field=models.CharField(max_length=120, verbose_name='Код характеристики'),
        ),
        migrations.AlterField(
            model_name='boardlistingattribute',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='board.boardlisting', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='boardlistingattribute',
            name='value_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Числовое значение'),
        ),
        migrations.AlterField(
            model_name='boardlistingattribute',
            name='value_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовое значение'),
        ),
        migrations.AlterField(
            model_name='boardlistingmedia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID медиа объявления'),
        ),
        migrations.AlterField(
            model_name='boardlistingmedia',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='board.boardlisting', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='boardlistingmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.mediafile', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='boardlistingmedia',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='boardlistingstatsdaily',
            name='contacts',
            field=models.IntegerField(default=0, verbose_name='Обращения'),
        ),
        migrations.AlterField(
            model_name='boardlistingstatsdaily',
            name='day',
            field=models.DateField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='boardlistingstatsdaily',
            name='favorites',
            field=models.IntegerField(default=0, verbose_name='Добавления в избранное'),
        ),
        migrations.AlterField(
            model_name='boardlistingstatsdaily',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_daily', to='board.boardlisting', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='boardlistingstatsdaily',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID жалобы'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.boardlisting', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='reason',
            field=models.CharField(max_length=80, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы'),
        ),
        migrations.AlterField(
            model_name='boardreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=24, verbose_name='Статус'),
        ),
    ]
