# Generated by Django 6.0.4 on 2026-05-05 13:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.gis.geos import Point


def copy_board_listing_coordinates_to_point(apps, schema_editor):
    BoardListing = apps.get_model('board', 'BoardListing')
    for listing in BoardListing.objects.exclude(lat__isnull=True).exclude(lng__isnull=True).iterator():
        listing.point = Point(float(listing.lng), float(listing.lat), srid=4326)
        listing.save(update_fields=['point'])


def copy_board_listing_coordinates_to_point_reverse(apps, schema_editor):
    BoardListing = apps.get_model('board', 'BoardListing')
    for listing in BoardListing.objects.exclude(point__isnull=True).iterator():
        listing.lat = listing.point.y
        listing.lng = listing.point.x
        listing.save(update_fields=['lat', 'lng'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_adcampaign_budget_spent_and_more'),
        ('board', '0003_alter_boardfavorite_created_at_and_more'),
        ('profile', '0004_remove_city_lat_remove_city_lng_city_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlisting',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.RunPython(
            copy_board_listing_coordinates_to_point,
            copy_board_listing_coordinates_to_point_reverse,
        ),
        migrations.RemoveField(
            model_name='boardlisting',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='boardlisting',
            name='lng',
        ),
        migrations.AddIndex(
            model_name='boardlisting',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='board_board_point_79dea8_gist'),
        ),
    ]
