FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /app/static /app/media

EXPOSE 8000

RUN chmod +x ./start.sh

CMD ["sh", "./start.sh"]