# Generated by Django 6.0.4 on 2026-05-04 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=120, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто совершил действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='after_data',
            field=models.JSONField(blank=True, null=True, verbose_name='После изменения'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before_data',
            field=models.JSONField(blank=True, null=True, verbose_name='До изменения'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID сущности'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=80, verbose_name='Тип сущности'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Центр карты (широта)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Центр карты (долгота)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=80, unique=True, verbose_name='URL-ключ города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.CharField(max_length=64, verbose_name='Таймзона'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='bucket',
            field=models.CharField(max_length=120, verbose_name='S3 bucket'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='MIME'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='object_key',
            field=models.TextField(verbose_name='S3 key'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='status',
            field=models.CharField(default='active', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='CDN/public URL'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID сущности'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Связанная сущность'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Доп. настройки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user', 'created_at'], name='profile_aud_actor_u_1a9340_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='profile_aud_entity__ebb94c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='profile_aud_action_df959b_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='profile_cit_slug_455d35_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='profile_cit_is_acti_ce8bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['owner', 'status'], name='profile_med_owner_i_cfffe6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['created_at'], name='profile_med_created_a59f48_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='profile_not_user_id_76607f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='profile_not_type_5c137d_idx'),
        ),
    ]
