# Generated by Django 6.0.4 on 2026-05-05 13:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.gis.geos import Point


def copy_city_coordinates_to_point(apps, schema_editor):
    City = apps.get_model('profile', 'City')
    for city in City.objects.exclude(lat__isnull=True).exclude(lng__isnull=True).iterator():
        city.point = Point(float(city.lng), float(city.lat), srid=4326)
        city.save(update_fields=['point'])


def copy_city_coordinates_to_point_reverse(apps, schema_editor):
    City = apps.get_model('profile', 'City')
    for city in City.objects.exclude(point__isnull=True).iterator():
        city.lat = city.point.y
        city.lng = city.point.x
        city.save(update_fields=['lat', 'lng'])


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_auditlog_id_alter_mediafile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Центр карты'),
        ),
        migrations.RunPython(copy_city_coordinates_to_point, copy_city_coordinates_to_point_reverse),
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lng',
        ),
        migrations.AddIndex(
            model_name='city',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='profile_cit_point_0b9d06_gist'),
        ),
    ]
