# Generated by Django 6.0.4 on 2026-05-04 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement', models.CharField(choices=[('feed', 'Лента'), ('search', 'Поиск'), ('map', 'Карта'), ('board', 'Объявления')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('views_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'На паузе'), ('finished', 'Завершена')], default='draft', max_length=24)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
            },
        ),
        migrations.CreateModel(
            name='AdminStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('users_count', models.IntegerField(default=0)),
                ('businesses_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ads_revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статистика админки за день',
                'verbose_name_plural': 'Статистика админки за дни',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('city', 'Город'), ('business', 'Бизнес'), ('board', 'Объявления')], max_length=24)),
                ('slug', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('icon', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['section', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=24)),
                ('reason', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кейс модерации',
                'verbose_name_plural': 'Кейсы модерации',
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=80)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Новая'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жалоба на отзыв',
                'verbose_name_plural': 'Жалобы на отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('target', models.CharField(choices=[('business', 'Бизнес'), ('seller', 'Продавец'), ('user', 'Пользователь')], max_length=24)),
                ('price_month', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
