# Generated by Django 6.0.4 on 2026-05-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('business', '0001_initial'),
        ('city', '0001_initial'),
        ('profile', '0002_alter_auditlog_action_alter_auditlog_actor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='business.business'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.city'),
        ),
        migrations.AddField(
            model_name='adminstatsdaily',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.city'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='admin_panel.category'),
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='city.review'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['target', 'is_active'], name='admin_panel_target_e1b8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['code'], name='admin_panel_code_e23bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'placement'], name='admin_panel_status_f5c0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['business', 'city'], name='admin_panel_busines_3b0de4_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['starts_at', 'ends_at'], name='admin_panel_starts__01ba3a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminstatsdaily',
            index=models.Index(fields=['city', 'day'], name='admin_panel_city_id_6a778a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminstatsdaily',
            index=models.Index(fields=['day'], name='admin_panel_day_7282df_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminstatsdaily',
            constraint=models.UniqueConstraint(fields=('city', 'day'), name='unique_admin_stats_city_day'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['section', 'parent'], name='admin_panel_section_10251b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='admin_panel_is_acti_9cb3fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('section', 'slug'), name='unique_category_section_slug'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['entity_type', 'entity_id'], name='admin_panel_entity__8e127d_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', 'created_at'], name='admin_panel_status_766f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', 'created_at'], name='admin_panel_status_d69321_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review'], name='admin_panel_review__f67c98_idx'),
        ),
    ]
