# Generated by Django 6.0.4 on 2026-05-04 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('business', '0001_initial'),
        ('city', '0002_alter_airequest_options_and_more'),
        ('profile', '0003_alter_auditlog_id_alter_mediafile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcampaign',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Потраченный бюджет'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Общий бюджет'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='clicks_count',
            field=models.IntegerField(default=0, verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID кампании'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='placement',
            field=models.CharField(choices=[('feed', 'Лента'), ('search', 'Поиск'), ('map', 'Карта'), ('board', 'Объявления')], max_length=40, verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'На паузе'), ('finished', 'Завершена')], default='draft', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество показов'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='ads_revenue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Выручка рекламы'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='businesses_count',
            field=models.IntegerField(default=0, verbose_name='Количество бизнесов'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='day',
            field=models.DateField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='orders_count',
            field=models.IntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='revenue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Общая выручка'),
        ),
        migrations.AlterField(
            model_name='adminstatsdaily',
            name='users_count',
            field=models.IntegerField(default=0, verbose_name='Количество пользователей'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='admin_panel.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('city', 'Город'), ('business', 'Бизнес'), ('board', 'Объявления')], max_length=24, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=120, verbose_name='URL-ключ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный модератор'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cases', to=settings.AUTH_USER_MODEL, verbose_name='Принял решение'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='entity_id',
            field=models.UUIDField(verbose_name='ID сущности'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='entity_type',
            field=models.CharField(max_length=64, verbose_name='Тип сущности'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID кейса'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина решения'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID жалобы'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reason',
            field=models.CharField(max_length=80, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL, verbose_name='Обработал'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='city.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='pending', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='code',
            field=models.CharField(max_length=80, unique=True, verbose_name='Код тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='features',
            field=models.JSONField(default=list, verbose_name='Возможности'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена за месяц'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='target',
            field=models.CharField(choices=[('business', 'Бизнес'), ('seller', 'Продавец'), ('user', 'Пользователь')], max_length=24, verbose_name='Целевая аудитория'),
        ),
    ]
