# Generated by Django 6.0.4 on 2026-05-04 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        ('business', '0001_initial'),
        ('profile', '0002_alter_auditlog_action_alter_auditlog_actor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('order', 'Заказ'), ('business', 'Бизнес'), ('support', 'Поддержка'), ('board', 'Объявление')], max_length=24)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_chats', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='profile.city')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.boardlisting')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='city.chatconversation')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('promo', 'Акция'), ('news', 'Новость'), ('event', 'Событие'), ('post', 'Пост')], max_length=24)),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('body', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удален'), ('pending', 'На модерации')], default='published', max_length=24)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('event_location', models.TextField(blank=True, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('promo_old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='profile.city')),
            ],
            options={
                'verbose_name': 'Пост ленты',
                'verbose_name_plural': 'Посты ленты',
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удален')], default='published', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='city.feedcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='city.feedpost')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.mediafile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='city.feedpost')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FeedReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(default='like', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='city.feedpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удален'), ('pending', 'На модерации')], default='published', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='business.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('hidden', 'Скрыта'), ('expired', 'Истекла')], default='active', max_length=24)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='business.business')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='profile.city')),
            ],
        ),
        migrations.CreateModel(
            name='StorySlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, null=True)),
                ('cta_label', models.CharField(blank=True, max_length=80, null=True)),
                ('cta_url', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.mediafile')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='city.story')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='profile.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='city_airequ_user_id_f1cc70_idx'), models.Index(fields=['city'], name='city_airequ_city_id_285412_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['buyer', 'last_message_at'], name='city_chatco_buyer_i_112330_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['seller', 'last_message_at'], name='city_chatco_seller__637f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['business'], name='city_chatco_busines_5319ae_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['listing'], name='city_chatco_listing_fbd459_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='city_chatme_convers_3fc062_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['city', 'status', 'published_at'], name='city_feedpo_city_id_4515ae_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['type'], name='city_feedpo_type_32cd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['business'], name='city_feedpo_busines_104984_idx'),
        ),
        migrations.AddIndex(
            model_name='feedcomment',
            index=models.Index(fields=['post', 'created_at'], name='city_feedco_post_id_1b27c0_idx'),
        ),
        migrations.AddIndex(
            model_name='feedcomment',
            index=models.Index(fields=['user'], name='city_feedco_user_id_3b40e3_idx'),
        ),
        migrations.AddIndex(
            model_name='feedreaction',
            index=models.Index(fields=['post'], name='city_feedre_post_id_3eda1f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedreaction',
            index=models.Index(fields=['user'], name='city_feedre_user_id_a9217c_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user', 'reaction'), name='unique_feed_reaction'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'business'), name='unique_user_business_follow'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['business', 'status'], name='city_review_busines_bce17d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='city_review_rating_896913_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='city_review_created_209264_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['city', 'status', 'expires_at'], name='city_story_city_id_abd61f_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['business'], name='city_story_busines_87ad32_idx'),
        ),
    ]
