# Generated by Django 6.0.4 on 2026-05-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airequest',
            options={'verbose_name': 'AI-запрос', 'verbose_name_plural': 'AI-запросы'},
        ),
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'verbose_name': 'Комментарий ленты', 'verbose_name_plural': 'Комментарии ленты'},
        ),
        migrations.AlterModelOptions(
            name='feedpostmedia',
            options={'ordering': ['sort_order'], 'verbose_name': 'Медиа поста', 'verbose_name_plural': 'Медиа постов'},
        ),
        migrations.AlterModelOptions(
            name='feedreaction',
            options={'verbose_name': 'Реакция на пост', 'verbose_name_plural': 'Реакции на посты'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Сторис', 'verbose_name_plural': 'Сторис'},
        ),
        migrations.AlterModelOptions(
            name='storyslide',
            options={'ordering': ['sort_order'], 'verbose_name': 'Слайд сторис', 'verbose_name_plural': 'Слайды сторис'},
        ),
    ]
