# Generated by Django 6.0.4 on 2026-05-04 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_boardfavorite_created_at_and_more'),
        ('business', '0002_alter_business_category_alter_business_city_and_more'),
        ('city', '0002_alter_airequest_options_and_more'),
        ('profile', '0003_alter_auditlog_id_alter_mediafile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='context',
            field=models.JSONField(default=dict, verbose_name='Контекст'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID AI-запроса'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='prompt',
            field=models.TextField(verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='response',
            field=models.JSONField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_chats', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='kind',
            field=models.CharField(choices=[('order', 'Заказ'), ('business', 'Бизнес'), ('support', 'Поддержка'), ('board', 'Объявление')], max_length=24, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего сообщения'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.boardlisting', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_chats', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='city.chatconversation', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID сообщения'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID комментария'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='city.feedcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='city.feedpost', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удален')], default='published', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='event_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='event_location',
            field=models.TextField(blank=True, null=True, verbose_name='Место события'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID поста'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='promo_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Старая цена акции'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена акции'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удален'), ('pending', 'На модерации')], default='published', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='tags',
            field=models.JSONField(default=list, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='title',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='type',
            field=models.CharField(choices=[('promo', 'Акция'), ('news', 'Новость'), ('event', 'Событие'), ('post', 'Пост')], max_length=24, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='feedpostmedia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID медиа поста'),
        ),
        migrations.AlterField(
            model_name='feedpostmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.mediafile', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='feedpostmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='city.feedpost', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='feedpostmedia',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='feedreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedreaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID реакции'),
        ),
        migrations.AlterField(
            model_name='feedreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='city.feedpost', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='feedreaction',
            name='reaction',
            field=models.CharField(default='like', max_length=24, verbose_name='Тип реакции'),
        ),
        migrations.AlterField(
            model_name='feedreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID подписки'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='business.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удален'), ('pending', 'На модерации')], default='published', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='story',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='story',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID сторис'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('hidden', 'Скрыта'), ('expired', 'Истекла')], default='active', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='cta_label',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='cta_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL кнопки'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID слайда'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.mediafile', verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='city.story', verbose_name='Сторис'),
        ),
    ]
