# Generated by Django 6.0.4 on 2026-05-04 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('profile', '0002_alter_auditlog_action_alter_auditlog_actor_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активен'), ('rejected', 'Отклонен'), ('blocked', 'Заблокирован')], default='draft', max_length=24)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='profile.city')),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_covers', to='profile.mediafile')),
                ('logo_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_logos', to='profile.mediafile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бизнес',
                'verbose_name_plural': 'Бизнесы',
            },
        ),
        migrations.CreateModel(
            name='BusinessAnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_check', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to='business.business')),
            ],
            options={
                'verbose_name': 'Аналитика бизнеса за день',
                'verbose_name_plural': 'Аналитика бизнеса за дни',
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geohash', models.CharField(blank=True, max_length=32, null=True)),
                ('is_main', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business.business')),
            ],
            options={
                'verbose_name': 'Адрес бизнеса',
                'verbose_name_plural': 'Адреса бизнеса',
            },
        ),
        migrations.CreateModel(
            name='BusinessWorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField()),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='business.business')),
            ],
            options={
                'verbose_name': 'Часы работы',
                'verbose_name_plural': 'Часы работы',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтвержден'), ('working', 'В работе'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=24)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=24)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('refunded', 'Возвращен'), ('failed', 'Ошибка')], default='pending', max_length=24)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('address', models.JSONField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='business.business')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='profile.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=80, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=220)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.product')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='ProductImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'В обработке'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=24)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_import_jobs', to='business.business')),
                ('file_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile')),
            ],
            options={
                'verbose_name': 'Импорт товаров',
                'verbose_name_plural': 'Импорты товаров',
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city', 'status'], name='business_bu_city_id_3f31e3_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'status'], name='business_bu_categor_3afb29_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='business_bu_owner_i_e66625_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='business_bu_slug_860a10_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_business_city_slug'),
        ),
        migrations.AddIndex(
            model_name='businessanalyticsdaily',
            index=models.Index(fields=['business', 'day'], name='business_bu_busines_891928_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessanalyticsdaily',
            constraint=models.UniqueConstraint(fields=('business', 'day'), name='unique_business_analytics_day'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(fields=['business'], name='business_bu_busines_97a898_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(fields=['lat', 'lng'], name='business_bu_lat_29b167_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(fields=['geohash'], name='business_bu_geohash_6d8c8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessworkinghours',
            constraint=models.UniqueConstraint(fields=('business', 'day_of_week'), name='unique_business_working_day'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='business_or_custome_a4fdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='business_or_busines_7e6a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['city', 'status'], name='business_or_city_id_b2418c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='business_or_payment_a35e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='business_pr_busines_ca8df7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='business_pr_categor_8b7c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='business_pr_price_a7b260_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='business_or_order_i_aad99b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='business_or_product_fbc795_idx'),
        ),
        migrations.AddIndex(
            model_name='productimportjob',
            index=models.Index(fields=['business', 'status'], name='business_pr_busines_de67c5_idx'),
        ),
        migrations.AddIndex(
            model_name='productimportjob',
            index=models.Index(fields=['created_at'], name='business_pr_created_bfe983_idx'),
        ),
    ]
