# Generated by Django 6.0.4 on 2026-05-04 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_adcampaign_budget_spent_and_more'),
        ('business', '0001_initial'),
        ('profile', '0003_alter_auditlog_id_alter_mediafile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='business',
            name='cover_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_covers', to='profile.mediafile', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID бизнеса'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_logos', to='profile.mediafile', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='business',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.CharField(max_length=160, verbose_name='URL-ключ'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('active', 'Активен'), ('rejected', 'Отклонен'), ('blocked', 'Заблокирован')], default='draft', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.TextField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='avg_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Конверсия'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='day',
            field=models.DateField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='orders_count',
            field=models.IntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='revenue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='businessanalyticsdaily',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='geohash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Геоиндекс'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID адреса'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Основной адрес'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='day_of_week',
            field=models.SmallIntegerField(verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID часов работы'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='businessworkinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='profile.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=24, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('refunded', 'Возвращен'), ('failed', 'Ошибка')], default='pending', max_length=24, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтвержден'), ('working', 'В работе'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID позиции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name_snapshot',
            field=models.CharField(max_length=220, verbose_name='Название на момент заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=220, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_import_jobs', to='business.business', verbose_name='Бизнес'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='error_rows',
            field=models.IntegerField(default=0, verbose_name='Ошибочных строк'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='errors',
            field=models.JSONField(default=list, verbose_name='Ошибки'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='file_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.mediafile', verbose_name='Файл импорта'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID импорта'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('processing', 'В обработке'), ('done', 'Готово'), ('failed', 'Ошибка')], default='queued', max_length=24, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='success_rows',
            field=models.IntegerField(default=0, verbose_name='Успешных строк'),
        ),
        migrations.AlterField(
            model_name='productimportjob',
            name='total_rows',
            field=models.IntegerField(default=0, verbose_name='Всего строк'),
        ),
    ]
