# Generated by Django 6.0.4 on 2026-05-05 13:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.gis.geos import Point


def copy_business_location_coordinates_to_point(apps, schema_editor):
    BusinessLocation = apps.get_model('business', 'BusinessLocation')
    for location in BusinessLocation.objects.exclude(lat__isnull=True).exclude(lng__isnull=True).iterator():
        location.point = Point(float(location.lng), float(location.lat), srid=4326)
        location.save(update_fields=['point'])


def copy_business_location_coordinates_to_point_reverse(apps, schema_editor):
    BusinessLocation = apps.get_model('business', 'BusinessLocation')
    for location in BusinessLocation.objects.exclude(point__isnull=True).iterator():
        location.lat = location.point.y
        location.lng = location.point.x
        location.save(update_fields=['lat', 'lng'])


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_category_alter_business_city_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businesslocation',
            name='business_bu_lat_29b167_idx',
        ),
        migrations.AddField(
            model_name='businesslocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.RunPython(
            copy_business_location_coordinates_to_point,
            copy_business_location_coordinates_to_point_reverse,
        ),
        migrations.RemoveField(
            model_name='businesslocation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='businesslocation',
            name='lng',
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='business_bu_point_145cf4_gist'),
        ),
    ]
